"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Persona_1 = require("./Persona");
var Direccion_1 = require("./Direccion");
var Telefono_1 = require("./Telefono");
var Mail_1 = require("./Mail");
var mail1 = new Mail_1.Mail("Personal", "mail1@personal.com");
var mail2 = new Mail_1.Mail("Trabajo", "mail2@trabajo.com");
var tel1 = new Telefono_1.Telefono("Móvil", "616121212");
var tel2 = new Telefono_1.Telefono("Casa", "616131313");
var tel3 = new Telefono_1.Telefono("Trabajo", "616141414");
var direc1 = new Direccion_1.Direccion("C/ Jazmín", 3, 29012, "Almería", "Almería", 5, "F");
var direc2 = new Direccion_1.Direccion("C/ de los Gatos", 42, 29650, "Mijas", "Málaga");
var direc3 = new Direccion_1.Direccion("Av. Rosales", 26, 25420, "Soportújar", "Granada", 2);
var persona1 = new Persona_1.Persona("Marina", "Rosales López", 54, "78245612F", "1969-03-12", "Amarillo", "Femenino");
persona1.agregarDireccion(direc1);
persona1.agregarDireccion(direc3);
persona1.agregarMail(mail1);
persona1.agregarMail(mail2);
persona1.agregarTelefono(tel1);
persona1.agregarTelefono(tel3);
persona1.agregarNota("Ir a la compra");
persona1.agregarNota("Llamar al seguro");
var persona2 = new Persona_1.Persona("Alberto", "Ramírez Salmorejo", 31, "84522336F", "1991-08-24", "Verde", "Masculino");
persona2.agregarDireccion(direc1);
persona2.agregarDireccion(direc2);
persona2.agregarMail(mail1);
persona2.agregarMail(mail2);
persona2.agregarTelefono(tel2);
persona2.agregarTelefono(tel3);
persona2.agregarNota("Recoger la ropa");
var persona3 = new Persona_1.Persona("Patricia", "Madueña Pérez", 70, "78245612F", "1953-01-28", "Aguamarina", "Femenino");
persona3.agregarDireccion(direc2);
persona3.agregarDireccion(direc3);
persona3.agregarMail(mail1);
persona3.agregarTelefono(tel1);
persona3.agregarTelefono(tel2);
persona3.agregarNota("Ir a clase de pintura");
persona3.agregarNota("Llamar al médico");
persona3.agregarNota("Recoger la ropa de la tintorería");
console.log(persona1);
console.log(persona2);
console.log(persona3);
var nuevaDireccion = new Direccion_1.Direccion("Plaza del Sol", 21, 22360, "Oviedo", "Asturias", 1, "A");
var nuevoMail = new Mail_1.Mail("Correo Basura", "mailnuevo@basura.com");
var nuevoTelefono = new Telefono_1.Telefono("Móvil 2", "666464646");
persona1.modificarRegistro("78245612F", nuevaDireccion, nuevoMail, nuevoTelefono);
console.log(persona1.direcciones);
console.log(persona1.mails);
console.log(persona1.telefonos);
